# Generated by Django 3.2.7 on 2021-09-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stbranch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STBranch',
        ),
    ]
